name: Build hi6250 Kernel

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out"
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt install bc bison build-essential curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick jq lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lunzip lzop pngcrush python-is-python3 python3 rr rsync schedtool simg2img squashfs-tools virtualenv xattr xmlstarlet xsltproc xz-utils zip zlib1g-dev -y

    - name: Get Toolchain
      run: |
        wget https://github.com/adithya2306/prebuilts_gcc_linux-x86_aarch64_aarch64-linaro-7/archive/refs/heads/master.tar.gz -O linaro-aarch64.tar.gz
        tar xf linaro-aarch64.tar.gz
        mv prebuilts_gcc_linux-x86_aarch64_aarch64-linaro-7-master linaro-toolchain

    - name: Set Build Date
      id: dob
      run: |
        echo "TIME=$(TZ=UTC-8 date +%d%m%y)" >> $GITHUB_OUTPUT

    - name: Build Kernel
      run: |
        export PATH=$(pwd)/linaro-toolchain/bin:$PATH
        make $KERNEL_CMDLINE phenix_defconfig
        make $KERNEL_CMDLINE -j$(nproc --all)
        tools/mkbootimg \
          --kernel out/arch/arm64/boot/Image.gz \
          --base 0x00478000 \
          --cmdline "loglevel=4 coherent_pool=512K page_tracker=on slub_min_objects=12 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" \
          --kernel_offset 0x00008000 \
          --ramdisk_offset 0x0ff88000 \
          --second_offset 0x00e88000 \
          --tags_offset 0x07988000 \
          --header_version 0 \
          --output Phenix_stock-${{ steps.dob.outputs.TIME }}.img

    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: A14Kernel-${{ steps.dob.outputs.TIME }}
        path: "A14Kernel-*.img"
